// src/oilSpillResults.ts

export interface OilSpillResult {
  image_name?: string;
  filename?: string;
  detection_count: number;
  max_confidence: number;
  [key: string]: unknown;
}

export interface DetectionSummary {
  images: number;
  detected: number;
  noSpill: number;
  totalDetections: number;
  averageConfidence: number;
}

/**
 * Load YOLO inference results generated by OceanSentinel.
 */
export async function loadOilSpillResults(): Promise<OilSpillResult[]> {
  const response = await fetch(
    "/aaaaaa-results/inference_results.json"
  );

  if (!response.ok) {
    throw new Error(
      `Failed to load YOLO inference results: ${response.status} ${response.statusText}`
    );
  }

  const data: unknown = await response.json();

  if (!Array.isArray(data)) {
    throw new Error(
      "Invalid YOLO inference results format. Expected an array."
    );
  }

  return data as OilSpillResult[];
}

/**
 * Calculate dashboard statistics from YOLO inference results.
 */
export function getDetectionSummary(
  results: OilSpillResult[]
): DetectionSummary {
  const images = results.length;

  const detected = results.filter(
    (item: OilSpillResult) => item.detection_count > 0
  ).length;

  const noSpill = images - detected;

  const totalDetections = results.reduce(
    (sum: number, item: OilSpillResult) =>
      sum + item.detection_count,
    0
  );

  const confidenceValues = results
    .filter(
      (item: OilSpillResult) =>
        item.detection_count > 0 &&
        typeof item.max_confidence === "number"
    )
    .map(
      (item: OilSpillResult) => item.max_confidence
    );

  const averageConfidence =
    confidenceValues.length > 0
      ? confidenceValues.reduce(
          (a: number, b: number) => a + b,
          0
        ) / confidenceValues.length
      : 0;

  return {
    images,
    detected,
    noSpill,
    totalDetections,
    averageConfidence,
  };
}